apiVersion: v1
kind: Service
metadata:
  name: clients-service
  labels:
    app: clients
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: clients
